# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_language_version:
    python: python3.6
exclude: >
    (?x)^(
        docs|
        examples|
        test/files
    )
repos:
-   repo: https://github.com/ambv/black
    rev: 19.3b0
    hooks:
    -   id: black
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: debug-statements
    -   id: trailing-whitespace
    -   id: flake8
