version: "3.7"

services:
  dashi:
    container_name: dashi
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      USE_BLEEDING_EDGE_ETL: "${USE_BLEEDING_EDGE_ETL}"

    restart: always
    ports:
      - '5000:5000'
    volumes:
      # location of qc-etl cache files
      - type: bind
        source: $HOME/qcetl
        target: /cache
      - type: bind
        source: ${LOG_FILE_LOCATION}
        target: /dashi/dashi.log
    secrets:
      - mongo_password

secrets:
  mongo_password:
    file: .mongopass
