[project]
name = "dashi"
# This version is unused.
# The app's real version comes from version.py.
version = "0.1.0"
description = "Dashi QC dashboard"
requires-python = ">=3.13"
dependencies = [
    "Flask-Caching~=2.4",
    "dash-bootstrap-components~=1.4",
    "pandas~=2.2",
    "Flask~=3.1",
    "dash~=3.0",
    "prometheus-flask-exporter~=0.22",
    "qc-etl",
    "sd-material-ui~=4.6",
    "python-dotenv~=1.1",
    "gevent~=26.5",
    "gunicorn~=23.0",
    "numpy~=2.2",
    "Werkzeug~=3.1",
]

[tool.uv]
package = false

[tool.uv.sources]
qc-etl = { git = "https://github.com/oicr-gsi/qc-etl.git", rev = "423388ac8c07255bc63a89eeb7301d00fb37f573" }

